### ISSUE TITLE
Task Breakdown for Milestone 3

### ISSUE THREAD

**Issue by Green-zy** [UBC-MDS/obesity-classifier-group17#20]
1. Script part  

Zanan

- [x] Download/extract data
- [x] Clean/transform data

Sepehr

- [x] Split and pre-process data
- [x] Exploratory data analysis

Yun

- [x] Last part of data validation
- [x] Split and pre-process data
- [x] Model fitting
- [x] Model evaluation

We will finalize the README.md together after finishing scripts.

3.  Convert the code to*.qmd file - Sepehr

4. Edit your report literate code document (*.qmd file) - On hold, do toghther or separate after the second lecture

5. Environment update - Yun

**Comment by Green-zy** [comment]
Is url link better of set id for uci data repo better to import our row data?

**Comment by Green-zy** [comment]
Is it possible to add data validation in the clean_data.py as well?

**Comment by zananpech** [comment]
I created two scripts download and clean data and validate function imported from src folder

**Comment by sep-he** [comment]
I created the eda script and pushed to the `script_report` branch.
Please pull the changes and run the following command in terminal from the root.
`python scripts/eda.py --training_data_split=data/processed/obesity_train.csv --plot_path=results/figures/`

**Comment by sep-he** [comment]
Zanan could you please add the validation steps 1 and 2 to the clean_data.py?

**Comment by sep-he** [comment]
Quarto file is updated and merged to main.
